name: 'capacitor-setup-ios'
description: ''
runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Install Swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: '5.10.0'
    - name: Cache node_modules
      id: node-modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: node-modules
    - name: Cache Pods
      id: pods
      uses: actions/cache@v4
      with:
        path: |
          ios/Pods
        key: pods
    - name: Cache Xcode
      uses: irgaly/xcode-cache@v1.7.2
      with:
        key: xcode-deriveddata
        restore-keys: xcode-deriveddata
    - name: Npm Install
      shell: bash
      run: npm i
    - name: Pod Install
      shell: bash
      run: cd ios; pod install; cd -
