name: 'capacitor-setup-android'
description: ''
runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: Cache node_modules
      id: node-modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: node-modules
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          android/.gradle
          ~/.gradle/caches
        key: gradle
    - name: Cache Android SDK
      id: aandroid-sdk
      uses: actions/cache@v4
      with:
        path: ~/Android/Sdk
        key: android-sdk
    - name: Cache AVD
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-29
    - name: Npm Install
      run: npm i
