disabled_rules:
  - identifier_name
  - force_try
  - type_body_length
  - file_length
  - opening_brace
  - function_parameter_count
  - for_where
  - trailing_comma

excluded:
  - Carthage
  - Pods
