$deploymentTargetVersion = '15.0'

platform :ios, $deploymentTargetVersion
inhibit_all_warnings!

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods

  pod 'AbrevvaSDK'
end

target 'PluginTests' do
  capacitor_pods
end

# Set deployment target for pods
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $deploymentTargetVersion
    end
  end
end
