name: build
permissions:
  contents: read
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Capacitor iOS
        uses: ./.github/actions/capacitor-setup-web
      - name: Run Build
        run: npm run verify:web
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Capacitor iOS
        uses: ./.github/actions/capacitor-setup-ios
      - name: Run Build
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app
        run: |
          cd ios
          xcodebuild \
          -quiet \
          -workspace Plugin.xcworkspace \
          -scheme Plugin \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Capacitor Android
        uses: ./.github/actions/capacitor-setup-android
      - name: Run Build
        run: npm run verify:android
