name: build
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Cache node_modules
        id: node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules
      - name: Npm Install
        run: npm i
      - name: Run Build
        run: npm run verify:web
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: '5.10.0'
      - name: Cache node_modules
        id: node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules
      - name: Cache Pods
        id: pods
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
          key: pods
      - name: Cache Xcode
        uses: irgaly/xcode-cache@v1.7.2
        with:
          key: xcode-deriveddata
          restore-keys: xcode-deriveddata
      - name: Npm Install
        run: npm i
      - name: Pod Install
        run: cd ios; pod install; cd -
      - name: Run Build
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app
        run: |
          cd ios
          xcodebuild \
          -quiet \
          -workspace Plugin.xcworkspace \
          -scheme Plugin \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'
  test_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
      - name: Cache node_modules
        id: node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            android/.gradle
            ~/.gradle/caches
          key: gradle
      - name: Cache Android SDK
        id: aandroid-sdk
        uses: actions/cache@v4
        with:
          path: ~/Android/Sdk
          key: android-sdk
      - name: Npm Install
        run: npm i
      - name: Run Build
        run: npm run verify:android
